config/routes.rb
VendaManager::Application.routes.draw do
  resources :empresas

  resources :fornecedors

  resources :item_nota_entradas

  resources :nota_entradas

  resources :rota_items

  match 'rota/pesquisa_kit',     :controller => 'kits', :action => 'pesquisa_kit'
  match 'rota/localiza_kit',     :controller => 'kits', :action => 'localiza_kit'
  match 'rota/inserir_kit_rota', :controller => 'kits', :action => 'inserir_kit_rota'
  match 'rota/excluir_item_kit', :controller => 'kits', :action => 'excluir_item_kit'
  
  match 'rota/pesquisa_brinde', :controller => 'kits', :action => 'pesquisa_brinde'  
  match 'rota/inserir_brinde_rota', :controller => 'kits', :action => 'inserir_brinde_rota'
  match 'rota/excluir_item_brinde', :controller => 'kits', :action => 'excluir_item_brinde'
  match 'rota/retorno_conferencia', :controller => 'rota',  :action => 'retorno_conferencia'
  match "rota/retorno_conferencia_result/:id", :controller => 'rota',  :action => 'retorno_conferencia_result'
  match 'rota/retorno_rota', :controller => 'rota', :action => 'retorno_rota'
  match "rota/retorno_rota_result/:id", :controller => 'rota',  :action => 'retorno_rota_result'
  match 'rota/processa_retorno_rota', :controller => 'rota', :action => 'processa_retorno_rota'
  match 'rota/processa_conferencia', :controller => 'rota', :action => 'processa_conferencia'
  
  match 'rota/nova', :controller => 'rota', :action => 'nova'

  resources :rota

  resources :cidades

  resources :usuarios

  resources :clientes

  resources :vendedors

  resources :consignados	

  resources :item_consignados

  resources :item_kits
	
  resources :kits

  resources :subgrupos

  resources :grupos

  resources :produtos
  
  resources :usuarios
  
  match '/pesquisa_nota_entrada', :controller => 'produtos', :action => 'pesquisa_produto_autocomplete'
  match '/localiza_produto_id',   :controller => 'produtos', :action => 'localiza_produto_id'
  match '/inseri_produto_nota',   :controller => 'nota_entradas', :action => 'inseri_produto_nota'
  match '/exclui_produto_nota', :to => 'nota_entradas#exclui_produto_nota'
  match '/fecha_nota_entrada', :to => 'nota_entradas#fecha_nota_entrada' 
  
  match '/pesquisa_descricao',    :controller => 'produtos', :action => 'pesquisa_item'
  match '/localiza_produto',      :controller => 'produtos', :action => 'localiza_produto'
  
  match '/inserir_produto_kit',   :controller => 'item_kits', :action => 'inserir_produto_kit'
  match '/excluir_item_kit',      :controller => 'item_kits', :action => 'excluir_item_kit'

  match '/kits/novo', :controller => 'kits', :action => 'novo'
  
  match 'sincronize/produtos', :controller => 'sincronize', :action => 'sincronize_produtos'
  match 'sincronize/clientes', :controller => 'sincronize', :action => 'sincronize_clientes'
  match 'sincronize/usuarios', :controller => 'sincronize', :action => 'sincronize_usuarios' 
  
  root :to => 'login#login'
  match '/home', to: 'home#index'
  match '/do_login', to: 'login#do_login'

end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/consignado.rb
class Consignado < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/estoque.rb
class Estoque < ActiveRecord::Base
  
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
end

app/models/item_kit.rb
class ItemKit < ActiveRecord::Base
  belongs_to :kit
end

app/models/kit.rb
class Kit < ActiveRecord::Base
  has_many :item_kit, :dependent => :destroy
end

app/models/nota_entrada.rb
class NotaEntrada < ActiveRecord::Base
end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/models/rota_item.rb
class RotaItem < ActiveRecord::Base
  belongs_to :rotum
end

app/models/rotum.rb
class Rotum < ActiveRecord::Base
  has_many :rota_items
end

app/models/subgrupo.rb
class Subgrupo < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  validates :empresa, :presence => true
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.find(:all, :conditions => ["empresa_id = ?", session[:usuario].empresa])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])
    @cliente.empresa_id = session[:usuario].empresa
    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/rota_helper.rb
module RotaHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :rg %><br />
    <%= f.text_field :rg %>
  </div>
  <div class="field">
    <%= f.label :logradouro %><br />
    <%= f.text_field :logradouro %>
  </div>
  <div class="field">
    <%= f.label :caixa_postal %><br />
    <%= f.text_field :caixa_postal %>
  </div>
  <div class="field">
    <%= f.label :cidade %><br />
    <%= f.text_field :cidade %>
  </div>
  <div class="field">
    <%= f.label :bairro %><br />
    <%= f.text_field :bairro %>
  </div>
  <div class="field">
    <%= f.label :uf %><br />
    <%= f.text_field :uf %>
  </div>
  <div class="field">
    <%= f.label :telefone1 %><br />
    <%= f.text_field :telefone1 %>
  </div>
  <div class="field">
    <%= f.label :telefone2 %><br />
    <%= f.text_field :telefone2 %>
  </div>
  <div class="field">
    <%= f.label :desativado %><br />
    <%= f.text_field :desativado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/_menu_clientes.html.erb
<script type="text/javascript">
	
	 $(document).ready(function () {
            setupLeftMenu();
	});
</script>
<div class="grid_2">
            <div class="box sidemenu">
                <div class="block" id="section-menu">
                    <ul class="section menu">
                        <li><a class="menuitem">Menu 1</a>
                            <ul class="submenu">
                                <li><a href="/clientes/new">Cadastro</a> </li>
                                <li><a href="/clientes">Lista</a> </li>
                              
                            </ul>
                        </li>
                        <li><a class="menuitem">Menu 2</a>
                            <ul class="submenu">
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                            </ul>
                        </li>
                        <li><a class="menuitem">Menu 3</a>
                            <ul class="submenu">
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                            </ul>
                        </li>
                        <li><a class="menuitem">Menu 4</a>
                            <ul class="submenu">
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                                <li><a>Submenu 6</a> </li>
                                <li><a>Submenu 7</a> </li>
                                <li><a>Submenu 8</a> </li>
                                <li><a>Submenu 9</a> </li>
                                <li><a>Submenu 10</a> </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

app/views/clientes/edit.html.erb
<%= render :partial => 'menu_clientes' %>
<div class="grid_10">
	<div class="box round">
<h2>Alterar Cliente</h2>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>
</div>
</div>

app/views/clientes/index.html.erb
<%= render :partial => 'menu_clientes' %>
<div class="grid_10">
	<div class="box round">
<h2>Listar clientes</h2>

<table>
  <tr>
    <th>Nome</th>
    <th>Cpf</th>
    <th>Rg</th>
    <th>Logradouro</th>
    <th>Caixa postal</th>
    <th>Cidade</th>
    <th>Bairro</th>
    <th>Uf</th>
    <th>Telefone1</th>
    <th>Telefone2</th>
    <th>Desativado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.cpf %></td>
    <td><%= cliente.rg %></td>
    <td><%= cliente.logradouro %></td>
    <td><%= cliente.caixa_postal %></td>
    <td><%= cliente.cidade %></td>
    <td><%= cliente.bairro %></td>
    <td><%= cliente.uf %></td>
    <td><%= cliente.telefone1 %></td>
    <td><%= cliente.telefone2 %></td>
    <td><%= cliente.desativado %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Destroy', cliente, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>
</div>
</div>

app/views/clientes/new.html.erb
<%= render :partial => 'menu_clientes' %>
<div class="grid_10">
	<div class="box round">
<h2>Novo Cliente</h2>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>
</div>
</div>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Cpf:</b>
  <%= @cliente.cpf %>
</p>

<p>
  <b>Rg:</b>
  <%= @cliente.rg %>
</p>

<p>
  <b>Logradouro:</b>
  <%= @cliente.logradouro %>
</p>

<p>
  <b>Caixa postal:</b>
  <%= @cliente.caixa_postal %>
</p>

<p>
  <b>Cidade:</b>
  <%= @cliente.cidade %>
</p>

<p>
  <b>Bairro:</b>
  <%= @cliente.bairro %>
</p>

<p>
  <b>Uf:</b>
  <%= @cliente.uf %>
</p>

<p>
  <b>Telefone1:</b>
  <%= @cliente.telefone1 %>
</p>

<p>
  <b>Telefone2:</b>
  <%= @cliente.telefone2 %>
</p>

<p>
  <b>Desativado:</b>
  <%= @cliente.desativado %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>