config/routes.rb
VendaManager::Application.routes.draw do
  resources :empresas

  resources :fornecedors

  resources :item_nota_entradas

  resources :nota_entradas

  resources :rota_items

  match 'rota/pesquisa_kit',     :controller => 'kits', :action => 'pesquisa_kit'
  match 'rota/localiza_kit',     :controller => 'kits', :action => 'localiza_kit'
  match 'rota/inserir_kit_rota', :controller => 'kits', :action => 'inserir_kit_rota'
  match 'rota/excluir_item_kit', :controller => 'kits', :action => 'excluir_item_kit'
  
  match 'rota/pesquisa_brinde', :controller => 'kits', :action => 'pesquisa_brinde'  
  match 'rota/inserir_brinde_rota', :controller => 'kits', :action => 'inserir_brinde_rota'
  match 'rota/excluir_item_brinde', :controller => 'kits', :action => 'excluir_item_brinde'
  match 'rota/retorno_conferencia', :controller => 'rota',  :action => 'retorno_conferencia'
  match "rota/retorno_conferencia_result/:id", :controller => 'rota',  :action => 'retorno_conferencia_result'
  match 'rota/retorno_rota', :controller => 'rota', :action => 'retorno_rota'
  match "rota/retorno_rota_result/:id", :controller => 'rota',  :action => 'retorno_rota_result'
  match 'rota/processa_retorno_rota', :controller => 'rota', :action => 'processa_retorno_rota'
  match 'rota/processa_conferencia', :controller => 'rota', :action => 'processa_conferencia'
  
  match 'rota/nova', :controller => 'rota', :action => 'nova'

  resources :rota

  resources :cidades

  resources :usuarios

  resources :clientes

  resources :vendedors

  resources :consignados	

  resources :item_consignados

  resources :item_kits
	
  resources :kits

  resources :subgrupos

  resources :grupos

  resources :produtos
  
  resources :usuarios
  
  match '/pesquisa_nota_entrada', :controller => 'produtos', :action => 'pesquisa_produto_autocomplete'
  match '/localiza_produto_id',   :controller => 'produtos', :action => 'localiza_produto_id'
  match '/inseri_produto_nota',   :controller => 'nota_entradas', :action => 'inseri_produto_nota'
  match '/exclui_produto_nota', :to => 'nota_entradas#exclui_produto_nota'
  match '/fecha_nota_entrada', :to => 'nota_entradas#fecha_nota_entrada' 
  
  match '/pesquisa_descricao',    :controller => 'produtos', :action => 'pesquisa_item'
  match '/localiza_produto',      :controller => 'produtos', :action => 'localiza_produto'
  
  match '/inserir_produto_kit',   :controller => 'item_kits', :action => 'inserir_produto_kit'
  match '/excluir_item_kit',      :controller => 'item_kits', :action => 'excluir_item_kit'

  match '/kits/novo', :controller => 'kits', :action => 'novo'
  
  match 'sincronize/produtos', :controller => 'sincronize', :action => 'sincronize_produtos'
  match 'sincronize/clientes', :controller => 'sincronize', :action => 'sincronize_clientes'
  match 'sincronize/usuarios', :controller => 'sincronize', :action => 'sincronize_usuarios' 
  
  root :to => 'login#login'
  match '/home', to: 'home#index'
  match '/do_login', to: 'login#do_login'

end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/consignado.rb
class Consignado < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/estoque.rb
class Estoque < ActiveRecord::Base
  
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
end

app/models/item_kit.rb
class ItemKit < ActiveRecord::Base
  belongs_to :kit
end

app/models/kit.rb
class Kit < ActiveRecord::Base
  has_many :item_kit, :dependent => :destroy
end

app/models/nota_entrada.rb
class NotaEntrada < ActiveRecord::Base
end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/models/rota_item.rb
class RotaItem < ActiveRecord::Base
  belongs_to :rotum
end

app/models/rotum.rb
class Rotum < ActiveRecord::Base
  has_many :rota_items
end

app/models/subgrupo.rb
class Subgrupo < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  validates :empresa, :presence => true
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
end

app/controllers/kits_controller.rb
require 'rubygems'
require 'json'

class KitsController < ApplicationController
  # GET /kits
  # GET /kits.json
  def index
    @kits = Kit.find(:all, :conditions => ["empresa = ?", session[:usuario].empresa])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kits }
    end
  end

  # GET /kits/1
  # GET /kits/1.json
  def show
    @kit = Kit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kit }
    end
  end

  # GET /kits/new
  # GET /kits/new.json
  def new
    @kit = Kit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kit }
    end
  end

  # GET /kits/1/edit
  def edit
    @kit = Kit.find(params[:id])
  end

  # POST /kits
  
  def create
    kit = Kit.new
    kit.descricao   = params[:kit][:descricao]
    kit.preco_venda = params[:kit][:preco_venda]
    kit.empresa = session[:usuario].empresa
    kit.save
    params.each do |key, value|
      if key.include? "quantidade"
        campo = key.split('_')
        itemKit = ItemKit.new
        itemKit.empresa = session[:usuario].empresa
        itemKit.quantidade = value
        itemKit.produto_id = campo[1]
        itemKit.kit_id = kit.id
        itemKit.save
      end
    end
    session[:items] = nil
    render :nothing => true
  end

  # PUT /kits/1
  # PUT /kits/1.json
  def update
    @kit = Kit.find(params[:id])

    respond_to do |format|
      if @kit.update_attributes(params[:kit])
        format.html { redirect_to @kit, notice: 'Kit was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @kit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kits/1
  # DELETE /kits/1.json
  def destroy
    @kit = Kit.find(params[:id])
    @kit.destroy

    respond_to do |format|
      format.html { redirect_to kits_url }
      format.json { head :ok }
    end
  end

	def novo
	  
	end
	
	def pesquisa_kit
    #render :layout => false
  end
  
  def localiza_kit  
    @kit = nil
    @kit = Kit.find(:all, :conditions => ["descricao LIKE ? and empresa = ?", params[:descricao]+ "%", session[:usuario].empresa])
    render :json => @kit.to_json
  end
  
  def inserir_kit_rota
    id = params[:id]
    @item = {:id => id}
  
    if session[:items_rota].nil?
      session[:items_rota] = Array.new
      session[:items_rota] << @item  
    else
      session[:items_rota] << @item
    end
    redirect_to '/rota/new'
  end
  
  def excluir_item_kit
    id = params[:id]
    session[:items_rota].each_with_index do |item, i|
      if item[:id] == id
        session[:items_rota].delete_at(i)
      end
    end
    redirect_to '/rota/new'
  end
  
  def pesquisa_brinde
    render :nothing => false
  end  
    
  def inserir_brinde_rota
    id = params[:id]
    @item = {:id => id}
  
    if session[:items_brinde].nil?
      session[:items_brinde] = Array.new
      session[:items_brinde] << @item  
    else
      session[:items_brinde] << @item
    end
    redirect_to '/rota/new'
  end
  
  def excluir_item_brinde
    id = params[:id]
    session[:items_brinde].each_with_index do |item, i|
      if item[:id] == id
        session[:items_brinde].delete_at(i)
      end
    end
    redirect_to '/rota/new'
  end
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/rota_helper.rb
module RotaHelper
end

app/views/kits/_form.html.erb
<%= form_for @kit do |f| %>
  <% if @kit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kit.errors.count, "error") %> prohibited this kit from being saved:</h2>

      <ul>
      <% @kit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
	<a href="/pesquisa_descricao">Inserir Item</a>
  </div>
	<div style="background-color: #B6B6B6	">
		<% if not session[:items].nil? %>
		<table><tr><th>Descricao</th><th>Quantidade</th><th>Excluir</th>
			<% session[:items].each do |item| %>
				<% produto = Produto.find(item[:id]) %>
			<tr>
				<td><%= produto.descricao %></td>
				<td><input type="text" size="3" id="quantidade_<%= produto.id %>" name="quantidade_<%= produto.id %>"></td>
				<td><a href="/excluir_item_kit?id=<%= produto.id %>">excluir</a></td>
			</tr>
			<% end %>
		</table>
		<% end %>
		
	</div>	
	<div class="field">
	    <%= f.label :descricao %><br />
	    <%= f.text_field :descricao %><br />
	    <%= f.label :Valor %><br />
	    <%= f.text_field :preco_venda, :size => 5%>
	    <input type="button" value="Criar Kit" onClick="validaKit();">
 	</div>

<% end %>


<script>

	var validaKit = function(){
		var erro = true;
		$('input[id*="quantidade_"]').each(
			function(i, e){
				if( $(e).val() == "" && $(e).val() < 1){
					erro = false;
					alert("Não pode haver Produto sem quantidade!");
					return false;
				}
			}
		);
		if(erro){
			//$('#new_kit').submit();
			preparaEnvio();
		}
	}
	
	var preparaEnvio = function(){
		var items = "";
		var produtos = new Array;
		$('input[id*="quantidade_"]').each(
			function(i, e){
				produtos.push(i);
				var elemento = $(e).attr("id");
				elementos = elemento.split("_");
				items += elementos[1];
				items += "_";
				items += $(e).val();
				if($('input[id*="quantidade_"]').length > (i+1)) items += "|"; 
			}
		);
		enviaKit(items);
	}
	
	var enviaKit = function(items){
		// var descricao   = $('#descricao').val();
		// var preco_venda = $('#preco_venda').val();
		// var csrf_token   = $('#csrf_token').val();
// 		
		// alert(csrf_token);
		// $.post(
			// '/kits/novo',
			// {items:items, descricao:descricao, preco_venda:preco_venda, csrf_token:csrf_token},
			// function(){}		
		// );		
		$("#new_kit").submit();
	}
</script>

app/views/kits/_menu_kits.html.erb
<script type="text/javascript">
	
	 $(document).ready(function () {
            setupLeftMenu();
	});
</script>
<div class="grid_2">
            <div class="box sidemenu">
                <div class="block" id="section-menu">
                    <ul class="section menu">
                        <li><a class="menuitem">Menu 1</a>
                            <ul class="submenu">
                                <li><a href="/kits/new">Cadastro</a> </li>
                                <li><a href="/kits">Lista</a> </li>
                              
                            </ul>
                        </li>
                        <li><a class="menuitem">Menu 2</a>
                            <ul class="submenu">
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                            </ul>
                        </li>
                        <li><a class="menuitem">Menu 3</a>
                            <ul class="submenu">
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                            </ul>
                        </li>
                        <li><a class="menuitem">Menu 4</a>
                            <ul class="submenu">
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                                <li><a>Submenu 6</a> </li>
                                <li><a>Submenu 7</a> </li>
                                <li><a>Submenu 8</a> </li>
                                <li><a>Submenu 9</a> </li>
                                <li><a>Submenu 10</a> </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

app/views/kits/edit.html.erb
<%= render :partial => 'menu_kits' %>
<div class="grid_10">
	<div class="box round">
<h2>Alterar kit</h2>

<%= render 'form' %>

<%= link_to 'Show', @kit %> |
<%= link_to 'Back', kits_path %>
</div>
</div>

app/views/kits/index.html.erb
<%= render :partial => 'menu_kits' %>
<div class="grid_10">
	<div class="box round">
<h2>Lista de Kits</h2>

<table>
  <tr>
    <th>Descricao</th>
    <th></th>
    
  </tr>

<% @kits.each do |kit| %>
  <tr>
    <td><label><%= kit.descricao %></label>
    
	    <% itemKit = ItemKit.find(:all, :conditions => ["kit_id = ?", kit.id]) %>
	    <% itemKit.each do |i|%>
	    <br />
	    	<% produto = Produto.find(i.id)%>
	    	<%= produto.descricao %>
	    <% end %>
  	</td>
  
    <td> <%= link_to 'Show', kit %> <%= link_to 'Edit', edit_kit_path(kit) %> 
    <%= link_to 'Destroy', kit, confirm: 'Are you sure?', method: :delete %></td>
  
<% end %>
</table>

<%= link_to 'New Kit', new_kit_path %>
</div>
</div>

app/views/kits/new.html.erb
<%= render :partial => 'menu_kits' %>
<div class="grid_10">
	<div class="box round">
<h2>Novo Kit</h2>

<%= render 'form' %>

<%= link_to 'Back', kits_path %>
</div>
</div>

app/views/kits/pesquisa_brinde.html.erb
<html>
<head>
  <%= javascript_include_tag "jquery.tmpl.min"%>
  <%= javascript_include_tag "jquery.tmplPlus.min"%>
<script>
	
	$(function(){
        $("#myTable").tablesorter(); 
	}); 	
	
	var markup = "<tr><td>${descricao}</td><td>${preco_venda}</td><td><a href='/rota/inserir_brinde_rota?id=${id}'>Inserir</a></td></tr>";

	$.template("template", markup);

	var produtosDescricao = function(descricao){		
		jQuery.getJSON(
			"/localiza_produto",
			{descricao:descricao},
			function(json){	
					$( "#conteudo" ).empty();
					$.tmpl("template", json).appendTo("#conteudo");	
			}
		);	
	}

	
</script>

</head>
<body>
<h1>Pesquisa Descrição</h1>
<a href='#' onClick='fechaJanela()'>Fechar janela</a>

<input type="text" onKeyUp="produtosDescricao(this.value);"/>


<table id="myTable" class="tablesorter">
	<thead>
		<tr>
			<td>Descricao</td>
			<td>Preco</td>
			<td>Função</td>
		</tr>
	<thead>
	<tbody id="conteudo"></tbody>
</table>

</body>
</html>

app/views/kits/pesquisa_kit.html.erb
<html>
<head>
  <%= javascript_include_tag "jquery.tmpl.min"%>
  <%= javascript_include_tag "jquery.tmplPlus.min"%>
<script>
	var retornar = function(){
		window.location="/rota/new"
	}
	
	$(function(){
        $("#myTable").tablesorter(); 
	}); 	
	
	var inserir_produto = function(id){
		var quantidade = $('#quantidade_'+id).val();
		$.post(
			'/inserir_kit_rota',
			{id:id},
			function(){
				
			}
		);
	}
	var markup = "<tr><td>${descricao}</td><td>${preco_venda}</td><td><a href='/rota/inserir_kit_rota?id=${id}'>Inserir</a></td></tr>";

	$.template("template", markup);

	var produtosDescricao = function(descricao){		
		jQuery.getJSON(
			"localiza_kit",
			{descricao:descricao},
			function(json){	
					$( "#conteudo" ).empty();
					$.tmpl("template", json).appendTo("#conteudo");	
			}
		);	
	}

	
</script>

</head>
<body>
<h3>Pesquisa Kits</h3>
<a href='#' onClick='retornar()'>Fechar janela</a>

<input type="text" onKeyUp="produtosDescricao(this.value);"/>


<table id="myTable" class="tablesorter">
	<thead>
		<tr>
			<td>Descricao</td>
			<td>Preco</td>
			<td>Função</td>
		</tr>
	<thead>
	<tbody id="conteudo"></tbody>
</table>

</body>
</html>

app/views/kits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descricao:</b>
  <%= @kit.descricao %>
</p>


<%= link_to 'Edit', edit_kit_path(@kit) %> |
<%= link_to 'Back', kits_path %>