config/routes.rb
VendaManager::Application.routes.draw do
  resources :empresas

  resources :fornecedors

  resources :item_nota_entradas

  resources :nota_entradas

  resources :rota_items

  match 'rota/pesquisa_kit',     :controller => 'kits', :action => 'pesquisa_kit'
  match 'rota/localiza_kit',     :controller => 'kits', :action => 'localiza_kit'
  match 'rota/inserir_kit_rota', :controller => 'kits', :action => 'inserir_kit_rota'
  match 'rota/excluir_item_kit', :controller => 'kits', :action => 'excluir_item_kit'
  
  match 'rota/pesquisa_brinde', :controller => 'kits', :action => 'pesquisa_brinde'  
  match 'rota/inserir_brinde_rota', :controller => 'kits', :action => 'inserir_brinde_rota'
  match 'rota/excluir_item_brinde', :controller => 'kits', :action => 'excluir_item_brinde'
  match 'rota/retorno_conferencia', :controller => 'rota',  :action => 'retorno_conferencia'
  match "rota/retorno_conferencia_result/:id", :controller => 'rota',  :action => 'retorno_conferencia_result'
  match 'rota/retorno_rota', :controller => 'rota', :action => 'retorno_rota'
  match "rota/retorno_rota_result/:id", :controller => 'rota',  :action => 'retorno_rota_result'
  match 'rota/processa_retorno_rota', :controller => 'rota', :action => 'processa_retorno_rota'
  match 'rota/processa_conferencia', :controller => 'rota', :action => 'processa_conferencia'
  
  match 'rota/nova', :controller => 'rota', :action => 'nova'

  resources :rota

  resources :cidades

  resources :usuarios

  resources :clientes

  resources :vendedors

  resources :consignados	

  resources :item_consignados

  resources :item_kits
	
  resources :kits

  resources :subgrupos

  resources :grupos

  resources :produtos
  
  resources :usuarios
  
  match '/pesquisa_nota_entrada', :controller => 'produtos', :action => 'pesquisa_produto_autocomplete'
  match '/localiza_produto_id',   :controller => 'produtos', :action => 'localiza_produto_id'
  match '/inseri_produto_nota',   :controller => 'nota_entradas', :action => 'inseri_produto_nota'
  match '/exclui_produto_nota', :to => 'nota_entradas#exclui_produto_nota'
  match '/fecha_nota_entrada', :to => 'nota_entradas#fecha_nota_entrada' 
  
  match '/pesquisa_descricao',    :controller => 'produtos', :action => 'pesquisa_item'
  match '/localiza_produto',      :controller => 'produtos', :action => 'localiza_produto'
  
  match '/inserir_produto_kit',   :controller => 'item_kits', :action => 'inserir_produto_kit'
  match '/excluir_item_kit',      :controller => 'item_kits', :action => 'excluir_item_kit'

  match '/kits/novo', :controller => 'kits', :action => 'novo'
  
  match 'sincronize/produtos', :controller => 'sincronize', :action => 'sincronize_produtos'
  match 'sincronize/clientes', :controller => 'sincronize', :action => 'sincronize_clientes'
  match 'sincronize/usuarios', :controller => 'sincronize', :action => 'sincronize_usuarios' 
  
  root :to => 'login#login'
  match '/home', to: 'home#index'
  match '/do_login', to: 'login#do_login'

end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/consignado.rb
class Consignado < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/estoque.rb
class Estoque < ActiveRecord::Base
  
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
end

app/models/item_kit.rb
class ItemKit < ActiveRecord::Base
  belongs_to :kit
end

app/models/kit.rb
class Kit < ActiveRecord::Base
  has_many :item_kit, :dependent => :destroy
end

app/models/nota_entrada.rb
class NotaEntrada < ActiveRecord::Base
end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/models/rota_item.rb
class RotaItem < ActiveRecord::Base
  belongs_to :rotum
end

app/models/rotum.rb
class Rotum < ActiveRecord::Base
  has_many :rota_items
end

app/models/subgrupo.rb
class Subgrupo < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  validates :empresa, :presence => true
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  # GET /cidades
  # GET /cidades.json
  def index
    @cidades = Cidade.find(:all, :conditions => ["empresa = ?", session[:usuario].empresa])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cidades }
    end
  end

  # GET /cidades/1
  # GET /cidades/1.json
  def show
    @cidade = Cidade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cidade }
    end
  end

  # GET /cidades/new
  # GET /cidades/new.json
  def new
    @cidade = Cidade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cidade }
    end
  end

  # GET /cidades/1/edit
  def edit
    @cidade = Cidade.find(params[:id])
  end

  # POST /cidades
  # POST /cidades.json
  def create
    @cidade = Cidade.new(params[:cidade])
    @cidade.empresa = session[:usuario].empresa

    respond_to do |format|
      if @cidade.save
        format.html { redirect_to @cidade, notice: 'Cidade was successfully created.' }
        format.json { render json: @cidade, status: :created, location: @cidade }
      else
        format.html { render action: "new" }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cidades/1
  # PUT /cidades/1.json
  def update
    @cidade = Cidade.find(params[:id])

    respond_to do |format|
      if @cidade.update_attributes(params[:cidade])
        format.html { redirect_to @cidade, notice: 'Cidade was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cidades/1
  # DELETE /cidades/1.json
  def destroy
    @cidade = Cidade.find(params[:id])
    @cidade.destroy

    respond_to do |format|
      format.html { redirect_to cidades_url }
      format.json { head :ok }
    end
  end
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/rota_helper.rb
module RotaHelper
end

app/views/cidades/_form.html.erb
<%= form_for(@cidade) do |f| %>
  <% if @cidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cidade.errors.count, "error") %> prohibited this cidade from being saved:</h2>

      <ul>
      <% @cidade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cidades/_menu_cidades.html.erb
<script type="text/javascript">
	
	 $(document).ready(function () {
            setupLeftMenu();
	});
</script>
<div class="grid_2">
            <div class="box sidemenu">
                <div class="block" id="section-menu">
                    <ul class="section menu">
                        <li><a class="menuitem">Menu 1</a>
                            <ul class="submenu">
                                <li><a href="/cidades/new">Cadastro</a> </li>
                                <li><a href="/cidades">Lista</a> </li>
                              
                            </ul>
                        </li>
                        <li><a class="menuitem">Menu 2</a>
                            <ul class="submenu">
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                            </ul>
                        </li>
                        <li><a class="menuitem">Menu 3</a>
                            <ul class="submenu">
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                            </ul>
                        </li>
                        <li><a class="menuitem">Menu 4</a>
                            <ul class="submenu">
                                <li><a>Submenu 1</a> </li>
                                <li><a>Submenu 2</a> </li>
                                <li><a>Submenu 3</a> </li>
                                <li><a>Submenu 4</a> </li>
                                <li><a>Submenu 5</a> </li>
                                <li><a>Submenu 6</a> </li>
                                <li><a>Submenu 7</a> </li>
                                <li><a>Submenu 8</a> </li>
                                <li><a>Submenu 9</a> </li>
                                <li><a>Submenu 10</a> </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

app/views/cidades/edit.html.erb
<%= render :partial => 'menu_cidades' %>
<div class="grid_10">
	<div class="box round">
<h2>Alterar Cidade</h2>

<%= render 'form' %>

<%= link_to 'Show', @cidade %> |
<%= link_to 'Back', cidades_path %>
</div>
</div>

app/views/cidades/index.html.erb
<%= render :partial => 'menu_cidades' %>
<div class="grid_10">
	<div class="box round">
<h2>Listar Cidades</h2>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cidades.each do |cidade| %>
  <tr>
    <td><%= cidade.nome %></td>
    <td><%= link_to 'Show', cidade %></td>
    <td><%= link_to 'Edit', edit_cidade_path(cidade) %></td>
    <td><%= link_to 'Destroy', cidade, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cidade', new_cidade_path %>
</div>
</div>

app/views/cidades/new.html.erb
<%= render :partial => 'menu_cidades' %>
<div class="grid_10">
	<div class="box round">
<h2>Nova Cidade</h2>

<%= render 'form' %>

<%= link_to 'Back', cidades_path %>
</div>
</div>

app/views/cidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cidade.nome %>
</p>


<%= link_to 'Edit', edit_cidade_path(@cidade) %> |
<%= link_to 'Back', cidades_path %>