config/routes.rb
VendaManager::Application.routes.draw do
  resources :empresas

  resources :fornecedors

  resources :item_nota_entradas

  resources :nota_entradas

  resources :rota_items

  match 'rota/pesquisa_kit',     :controller => 'kits', :action => 'pesquisa_kit'
  match 'rota/localiza_kit',     :controller => 'kits', :action => 'localiza_kit'
  match 'rota/inserir_kit_rota', :controller => 'kits', :action => 'inserir_kit_rota'
  match 'rota/excluir_item_kit', :controller => 'kits', :action => 'excluir_item_kit'
  
  match 'rota/pesquisa_brinde', :controller => 'kits', :action => 'pesquisa_brinde'  
  match 'rota/inserir_brinde_rota', :controller => 'kits', :action => 'inserir_brinde_rota'
  match 'rota/excluir_item_brinde', :controller => 'kits', :action => 'excluir_item_brinde'
  match 'rota/retorno_conferencia', :controller => 'rota',  :action => 'retorno_conferencia'
  match "rota/retorno_conferencia_result/:id", :controller => 'rota',  :action => 'retorno_conferencia_result'
  match 'rota/retorno_rota', :controller => 'rota', :action => 'retorno_rota'
  match "rota/retorno_rota_result/:id", :controller => 'rota',  :action => 'retorno_rota_result'
  match 'rota/processa_retorno_rota', :controller => 'rota', :action => 'processa_retorno_rota'
  match 'rota/processa_conferencia', :controller => 'rota', :action => 'processa_conferencia'
  
  match 'rota/nova', :controller => 'rota', :action => 'nova'

  resources :rota

  resources :cidades

  resources :usuarios

  resources :clientes

  resources :vendedors

  resources :consignados	

  resources :item_consignados

  resources :item_kits
	
  resources :kits

  resources :subgrupos

  resources :grupos

  resources :produtos
  
  resources :usuarios
  
  match '/pesquisa_nota_entrada', :controller => 'produtos', :action => 'pesquisa_produto_autocomplete'
  match '/localiza_produto_id',   :controller => 'produtos', :action => 'localiza_produto_id'
  match '/inseri_produto_nota',   :controller => 'nota_entradas', :action => 'inseri_produto_nota'
  match '/exclui_produto_nota', :to => 'nota_entradas#exclui_produto_nota'
  match '/fecha_nota_entrada', :to => 'nota_entradas#fecha_nota_entrada' 
  
  match '/pesquisa_descricao',    :controller => 'produtos', :action => 'pesquisa_item'
  match '/localiza_produto',      :controller => 'produtos', :action => 'localiza_produto'
  
  match '/inserir_produto_kit',   :controller => 'item_kits', :action => 'inserir_produto_kit'
  match '/excluir_item_kit',      :controller => 'item_kits', :action => 'excluir_item_kit'

  match '/kits/novo', :controller => 'kits', :action => 'novo'
  
  match 'sincronize/produtos', :controller => 'sincronize', :action => 'sincronize_produtos'
  match 'sincronize/clientes', :controller => 'sincronize', :action => 'sincronize_clientes'
  match 'sincronize/usuarios', :controller => 'sincronize', :action => 'sincronize_usuarios' 
  
  root :to => 'login#login'
  match '/home', to: 'home#index'
  match '/do_login', to: 'login#do_login'

end

app/models/cidade.rb
class Cidade < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/consignado.rb
class Consignado < ActiveRecord::Base
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
end

app/models/estoque.rb
class Estoque < ActiveRecord::Base
  
end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
end

app/models/grupo.rb
class Grupo < ActiveRecord::Base
end

app/models/item_kit.rb
class ItemKit < ActiveRecord::Base
  belongs_to :kit
end

app/models/kit.rb
class Kit < ActiveRecord::Base
  has_many :item_kit, :dependent => :destroy
end

app/models/nota_entrada.rb
class NotaEntrada < ActiveRecord::Base
end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/models/rota_item.rb
class RotaItem < ActiveRecord::Base
  belongs_to :rotum
end

app/models/rotum.rb
class Rotum < ActiveRecord::Base
  has_many :rota_items
end

app/models/subgrupo.rb
class Subgrupo < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  validates :empresa, :presence => true
end

app/models/vendedor.rb
class Vendedor < ActiveRecord::Base
end

app/controllers/consignados_controller.rb
class ConsignadosController < ApplicationController
  # GET /consignados
  # GET /consignados.json
  def index
    @consignados = Consignado.find(:all, :conditions => ["empresa = ?", session[:usuario].empresa])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @consignados }
    end
  end

  # GET /consignados/1
  # GET /consignados/1.json
  def show
    @consignado = Consignado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @consignado }
    end
  end

  # GET /consignados/new
  # GET /consignados/new.json
  def new
    @consignado = Consignado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @consignado }
    end
  end

  # GET /consignados/1/edit
  def edit
    @consignado = Consignado.find(params[:id])
  end

  # POST /consignados
  # POST /consignados.json
  def create
    @consignado = Consignado.new(params[:consignado])
    @consignado.empresa = session[:usuario].empresa
    respond_to do |format|
      if @consignado.save
        format.html { redirect_to @consignado, notice: 'Consignado was successfully created.' }
        format.json { render json: @consignado, status: :created, location: @consignado }
      else
        format.html { render action: "new" }
        format.json { render json: @consignado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /consignados/1
  # PUT /consignados/1.json
  def update
    @consignado = Consignado.find(params[:id])

    respond_to do |format|
      if @consignado.update_attributes(params[:consignado])
        format.html { redirect_to @consignado, notice: 'Consignado was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @consignado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consignados/1
  # DELETE /consignados/1.json
  def destroy
    @consignado = Consignado.find(params[:id])
    @consignado.destroy

    respond_to do |format|
      format.html { redirect_to consignados_url }
      format.json { head :ok }
    end
  end
end

app/helpers/consignados_helper.rb
module ConsignadosHelper
end

app/helpers/grupos_helper.rb
module GruposHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kits_helper.rb
module KitsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/rota_helper.rb
module RotaHelper
end

app/views/consignados/_form.html.erb
<%= form_for(@consignado) do |f| %>
  <% if @consignado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consignado.errors.count, "error") %> prohibited this consignado from being saved:</h2>

      <ul>
      <% @consignado.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliente_id %><br />
    <%= f.number_field :cliente_id %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.datetime_select :data %>
  </div>
  <div class="field">
    <%= f.label :proxima_cobranca %><br />
    <%= f.datetime_select :proxima_cobranca %>
  </div>
  <div class="field">
    <%= f.label :prazo_dias %><br />
    <%= f.number_field :prazo_dias %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consignados/edit.html.erb
<h1>Editing consignado</h1>

<%= render 'form' %>

<%= link_to 'Show', @consignado %> |
<%= link_to 'Back', consignados_path %>

app/views/consignados/index.html.erb
<h1>Listing consignados</h1>

<table>
  <tr>
    <th>Cliente</th>
    <th>Data</th>
    <th>Proxima cobranca</th>
    <th>Prazo dias</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @consignados.each do |consignado| %>
  <tr>
    <td><%= consignado.cliente_id %></td>
    <td><%= consignado.data %></td>
    <td><%= consignado.proxima_cobranca %></td>
    <td><%= consignado.prazo_dias %></td>
    <td><%= link_to 'Show', consignado %></td>
    <td><%= link_to 'Edit', edit_consignado_path(consignado) %></td>
    <td><%= link_to 'Destroy', consignado, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Consignado', new_consignado_path %>

app/views/consignados/new.html.erb
<h1>New consignado</h1>

<%= render 'form' %>

<%= link_to 'Back', consignados_path %>

app/views/consignados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <%= @consignado.cliente_id %>
</p>

<p>
  <b>Data:</b>
  <%= @consignado.data %>
</p>

<p>
  <b>Proxima cobranca:</b>
  <%= @consignado.proxima_cobranca %>
</p>

<p>
  <b>Prazo dias:</b>
  <%= @consignado.prazo_dias %>
</p>


<%= link_to 'Edit', edit_consignado_path(@consignado) %> |
<%= link_to 'Back', consignados_path %>